apiVersion: apps/v1
kind: Deployment

metadata:
  name: iris-api-dev
  namespace: dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: iris-api-dev

  template:
    metadata:
      labels:
        app: iris-api-dev

    spec:
      containers:
      - name: iris-api
        image: 494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-model:IMAGE_TAG 

        ports:
        - containerPort: 8080
