apiVersion: v1
kind: Service

metadata:
  name: iris-api-dev
  namespace: dev

spec:
  type: LoadBalancer

  selector:
    app: iris-api-dev

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
