apiVersion: v1
kind: Service
metadata:
  name: iris-api-dev
  labels:
    app: iris-api
    env: dev

spec:
  type: ClusterIP
  selector:
    app: iris-api
    env: dev

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

