apiVersion: v1
kind: Service

metadata:
  name: iris-inference
  namespace: dev

spec:

  selector:
    app: iris-inference

  ports:

  - protocol: TCP
    port: 80
    targetPort: 8080

  type: LoadBalancer
