apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris-prod
  template:
    metadata:
      labels:
        app: iris-prod
    spec:
      containers:
        - name: iris-container
          image: 494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:latest
          ports:
            - containerPort: 5000

