architectures:
- linux/amd64
- linux/arm64
dashboards:
  istio-extension-dashboard: 13277
  istio-mesh-dashboard: 7639
  istio-performance-dashboard: 11829
  istio-service-dashboard: 7636
  istio-workload-dashboard: 7630
  pilot-dashboard: 7645
  ztunnel-dashboard: 21306
dependencies:
  api:
    goversionenabled: true
    sha: 7fea5efd57cad1f60404fdb730306a7d8e8821bd
  client-go:
    goversionenabled: true
    sha: 34bf90f81feb53af04489482a3392986c47515ee
  envoy:
    sha: 07bece5476a5e3c95c8b0a3df4e41d3dd0769df4
  istio:
    sha: 2300e2458ab713c2c514a58da1ea8b03343ada7e
  proxy:
    sha: 1fdadc301aaaa0326255f82bd27387a0e101c164
  release-builder:
    sha: e8b00db1ac93cd14ac7355d805a3f6433953913e
  test-infra:
    sha: 3a836a428b45c3d76fc9b67d57903432fbac19c7
  tools:
    sha: 21a0e5266c00c494f01b0a3f7060523c8464b12b
  ztunnel:
    sha: 4225e92aa753b1bdba800fe975f03e131f8cc257
docker: docker.io/istio
dockerOutput: tar
skipGenerateBillOfMaterials: false
version: 1.29.0
