apiVersion: v1
kind: Service
metadata:
  name: iris-api-qa
  labels:
    app: iris-api
    env: qa

spec:
  type: ClusterIP
  selector:
    app: iris-api
    env: qa

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

