name: CI-CD Iris API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login ECR
        run: |
          aws ecr get-login-password --region us-east-2 \
          | docker login --username AWS --password-stdin 494722910828.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t iris-api .

      - name: Tag Docker Image
        run: |
          docker tag iris-api:latest 494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:latest

      - name: Push Docker Image
        run: |
          docker push 494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:latest

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-2 --name ml-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

