name: CI-CD-ML

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login ECR
        run: |
          aws ecr get-login-password --region us-east-2 | \
          docker login --username AWS --password-stdin 494722910828.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Docker
        run: docker build -t iris-api .

      - name: Tag Image
        run: docker tag iris-api 494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:latest

      - name: Push Image
        run: docker push 494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy DEV
        if: github.ref == 'refs/heads/dev'
        run: kubectl apply -f deployment-dev.yaml -n dev

      - name: Deploy QA
        if: github.ref == 'refs/heads/qa'
        run: kubectl apply -f deployment-qa.yaml -n qa

      - name: Deploy PROD
        if: github.ref == 'refs/heads/main'
        run: kubectl apply -f deployment-prod.yaml -n prod

