name: Iris CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: iris-api
  ACCOUNT_ID: 494722910828
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Image
        run: docker build -t iris-api:$IMAGE_TAG .

      - name: Tag Image
        run: |
          docker tag iris-api:$IMAGE_TAG \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Image
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ml-cluster --region $AWS_REGION

      - name: Replace Image Tag DEV
        run: sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/dev/deployment.yaml

      - name: Deploy DEV
        run: kubectl apply -f k8s/dev/deployment.yaml

  deploy-qa:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ml-cluster --region $AWS_REGION

      - name: Replace Image Tag QA
        run: sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/qa/deployment.yaml

      - name: Deploy QA
        run: kubectl apply -f k8s/qa/deployment.yaml

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ml-cluster --region $AWS_REGION

      - name: Replace Image Tag PROD
        run: sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/prod/deployment.yaml

      - name: Deploy PROD
        run: kubectl apply -f k8s/prod/deployment.yaml

