name: Iris CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: iris-api
  ACCOUNT_ID: 494722910828
  IMAGE_TAG: v1.0.${{ github.run_number }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Image
        run: docker build -t iris-api .

      - name: Tag Image
        run: |
          docker tag iris-api:latest \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Image
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ml-cluster --region us-east-2

      - name: Deploy DEV
        run: |
          kubectl set image deployment/iris-api-dev iris-api=494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:$IMAGE_TAG

  deploy-qa:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ml-cluster --region us-east-2

      - name: Deploy QA
        run: |
          kubectl set image deployment/iris-api-qa iris-api=494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:$IMAGE_TAG

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ml-cluster --region us-east-2

      - name: Deploy PROD
        run: |
          kubectl set image deployment/iris-api-prod iris-api=494722910828.dkr.ecr.us-east-2.amazonaws.com/iris-api:$IMAGE_TAG

